version: "3.8"
services:
  web:
    container_name: web-magang
    image: php:8.0-apache
    ports:
      - 8000:80
    volumes:
      - ./web:/var/www/html/
  api:
    container_name: api-magang
    image: php:8.0-apache
    ports:
      - 8001:80
    volumes:
      - ./api:/var/www/html/
  db:
    container_name: db-magang
    image: mysql
    ports: 
      - 9906:3306
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    restart: always
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin-magang
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db